DNS1: 8.8.8.8
DNS2: 8.8.4.4
adlists:
- https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
- https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
- https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
- https://v.firebog.net/hosts/static/w3kbl.txt
- https://v.firebog.net/hosts/Easyprivacy.txt
- https://v.firebog.net/hosts/Prigent-Ads.txt
- https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
- https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
- https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
- https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
- https://v.firebog.net/hosts/Prigent-Crypto.txt
- https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
- https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
- https://phishing.army/download/phishing_army_blocklist_extended.txt
- https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
- https://v.firebog.net/hosts/RPiList-Malware.txt
- https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
- https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts
- https://urlhaus.abuse.ch/downloads/hostfile/
- https://lists.cyberhost.uk/malware.txt
- https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/pro.txt
- https://hosts-file.net/grm.txt
- https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt
- https://someonewhocares.org/hosts/zero/hosts
- https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts
- https://winhelp2002.mvps.org/hosts.txt
- https://v.firebog.net/hosts/neohostsbasic.txt
- https://raw.githubusercontent.com/RooneyMcNibNug/pihole-stuff/master/SNAFU.txt
- https://paulgb.github.io/BarbBlock/blacklists/hosts-file.txt
admin:
  annotations: null
  enabled: true
  existingSecret: ""
  passwordKey: password
adminPassword: admin
affinity: {}
antiaff:
  avoidRelease: pihole1
  enabled: false
  namespaces: []
  strict: true
blacklist: {}
capabilities: {}
customVolumes:
  config: {}
  enabled: false
deploymentAnnotations: {}
dnsHostPort:
  enabled: false
  port: 53
dnsmasq:
  additionalHostsEntries: []
  customCnameEntries: []
  customDnsEntries:
  - address=/.home.devopsinthe.cloud/192.168.68.100
  enableCustomDnsMasq: true
  staticDhcpEntries: []
  upstreamServers: []
doh:
  command: []
  enabled: false
  envVars: {}
  monitoring:
    podMonitor:
      enabled: false
  name: cloudflared
  probes:
    liveness:
      enabled: true
      failureThreshold: 10
      initialDelaySeconds: 60
      probe:
        exec:
          command:
          - nslookup
          - -po=5053
          - cloudflare.com
          - 127.0.0.1
      timeoutSeconds: 5
    readiness:
      enabled: true
      failureThreshold: 10
      initialDelaySeconds: 60
      probe:
        exec:
          command:
          - nslookup
          - -po=5053
          - cloudflare.com
          - 127.0.0.1
      timeoutSeconds: 5
  pullPolicy: IfNotPresent
  repository: crazymax/cloudflared
  tag: latest
dualStack:
  enabled: false
extraContainers: []
extraEnvVars:
  FTLCONF_dns_listeningMode: all
  TZ: America/New_York
extraEnvVarsSecret: {}
extraInitContainers: []
extraObjects: []
extraVolumeMounts: {}
extraVolumes: {}
ftl: {}
hostNetwork: "false"
hostname: ""
image:
  pullPolicy: IfNotPresent
  repository: pihole/pihole
  tag: ""
ingress:
  annotations: {}
  enabled: true
  hosts:
  - pihole.home.devopsinthe.cloud
  path: /
  pathType: ImplementationSpecific
  tls: []
maxSurge: 1
maxUnavailable: 1
monitoring:
  podMonitor:
    enabled: false
  sidecar:
    enabled: false
    image:
      pullPolicy: IfNotPresent
      repository: ekofr/pihole-exporter
      tag: v1.0.0
    port: 9617
    resources:
      limits:
        memory: 128Mi
nodeSelector: {}
persistentVolumeClaim:
  accessModes:
  - ReadWriteOnce
  annotations: {}
  enabled: true
  size: 500Mi
podAnnotations: {}
podDisruptionBudget:
  enabled: false
  minAvailable: 1
podDnsConfig:
  enabled: true
  nameservers:
  - 127.0.0.1
  - 8.8.8.8
  policy: None
privileged: "false"
probes:
  liveness:
    enabled: true
    failureThreshold: 10
    initialDelaySeconds: 60
    port: http
    scheme: HTTP
    timeoutSeconds: 5
    type: httpGet
  readiness:
    enabled: true
    failureThreshold: 10
    initialDelaySeconds: 60
    port: http
    scheme: HTTP
    timeoutSeconds: 5
    type: httpGet
regex: {}
replicaCount: 1
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi
serviceDhcp:
  annotations: {}
  enabled: false
  externalTrafficPolicy: Local
  extraLabels: {}
  loadBalancerClass: ""
  loadBalancerIP: ""
  loadBalancerIPv6: ""
  nodePort: ""
  port: 67
  type: NodePort
serviceDns:
  annotations: {}
  externalTrafficPolicy: Local
  extraLabels: {}
  loadBalancerClass: ""
  loadBalancerIP: 192.168.68.100
  loadBalancerIPv6: ""
  mixedService: true
  nodePort: ""
  port: 53
  type: LoadBalancer
serviceWeb:
  annotations: {}
  externalTrafficPolicy: Local
  extraLabels: {}
  http:
    enabled: true
    nodePort: ""
    port: 80
  https:
    enabled: false
    nodePort: ""
    port: 443
  loadBalancerClass: ""
  loadBalancerIP: ""
  loadBalancerIPv6: ""
  type: ClusterIP
strategyType: RollingUpdate
tolerations: []
topologySpreadConstraints: []
virtualHost: pihole.home.devopsinthe.cloud
webHttp: "80"
webHttps: "443"
whitelist: {}
